/**
 * Hermes ↔ HIPP0 integration contract.
 *
 * Single source of truth for the HTTP payloads exchanged between the HIPP0
 * server and a Hermes runtime that is acting as the Hipp0MemoryProvider.
 *
 * This file is imported by the `/api/hermes/*` route handlers on the server
 * side and is the spec the sibling Hermes Claude Code instance codes against.
 *
 * Design notes:
 *
 *   - `project_id` is REQUIRED on every request. HIPP0 is multi-tenant.
 *   - `session_id` is server-generated. Never accept a client-chosen session
 *     id. Hermes must call `/api/hermes/session/start` first.
 *   - `agent_id` is also server-generated by `/api/hermes/register` and must
 *     be persisted by Hermes in `~/.hermes/agents/<name>/config.yaml` so that
 *     subsequent capture/compile calls are bound to the right agent row.
 *   - Existing endpoints (`POST /api/capture`, `POST /api/compile`,
 *     `POST /api/outcomes`) are REUSED with their real shapes — see
 *     `routes/capture.ts`, `routes/compile.ts`, `routes/outcomes.ts`.
 *   - New endpoints live under the `/api/hermes/*` namespace to avoid
 *     colliding with the existing `/api/agents/*` routes which power the
 *     HIPP0 Agent Registry (a different concept — those are "agents" as API
 *     consumers; hermes agents are runtime personas).
 *   - Everything here is pure-data. No runtime schema validators — the route
 *     handlers use the existing `requireUUID`, `requireString`,
 *     `optionalString` helpers from `routes/validation.ts`.
 */

// ---------------------------------------------------------------------------
// Common
// ---------------------------------------------------------------------------

/** Valid platforms a Hermes session can be running on. */
export type HermesPlatform = 'telegram' | 'discord' | 'slack' | 'whatsapp' | 'signal' | 'web' | 'cli';

/** The `source` value Hermes uses when calling POST /api/capture. */
export const HERMES_CAPTURE_SOURCE = 'hermes' as const;

/** Regex used to validate `agent_name` on both sides of the wire. */
export const HERMES_AGENT_NAME_RE = /^[a-z][a-z0-9_-]{0,63}$/;

// ---------------------------------------------------------------------------
// POST /api/hermes/register — register or upsert a persistent agent
// ---------------------------------------------------------------------------

export interface HermesRegisterRequest {
  project_id: string;             // UUID, required
  agent_name: string;             // matches HERMES_AGENT_NAME_RE
  soul: string;                   // SOUL.md content, max 100_000 chars
  config: HermesAgentConfig;      // persisted runtime config
}

export interface HermesAgentConfig {
  model: string;                          // e.g. "anthropic/claude-sonnet-4-6"
  toolset?: string;                       // Hermes toolset name, optional
  platform_access?: HermesPlatform[];     // which platforms this agent may serve
  metadata?: Record<string, unknown>;     // free-form, opaque to HIPP0
}

export interface HermesRegisterResponse {
  agent_id: string;    // server-generated UUID, stable across restarts
  agent_name: string;
  created: boolean;    // true on insert, false on update
}

// ---------------------------------------------------------------------------
// POST /api/hermes/session/start — begin a new runtime session
// ---------------------------------------------------------------------------

export interface HermesSessionStartRequest {
  project_id: string;             // UUID, required
  agent_name: string;             // must be a registered agent
  platform: HermesPlatform;
  /**
   * External user identifier. For Telegram this is the Telegram user_id, for
   * Discord the Discord user id, for web/cli the authenticated hipp0 user id
   * if any. Nullable when the runtime is unattended (cron, skill).
   */
  external_user_id?: string | null;
  /** External chat/room identifier (Telegram chat_id, Discord channel id). */
  external_chat_id?: string | null;
  /** Optional session metadata — platform-specific bag. */
  metadata?: Record<string, unknown>;
}

export interface HermesSessionStartResponse {
  session_id: string;     // server-generated UUID, use in subsequent capture/compile
  conversation_id: string;// UUID of the hermes_conversations row backing this session
  started_at: string;     // ISO-8601
}

// ---------------------------------------------------------------------------
// POST /api/hermes/session/end — flush + rolling summary
// ---------------------------------------------------------------------------

export interface HermesSessionEndRequest {
  session_id: string;             // UUID from start_session
  /**
   * Optional end-of-turn outcome signal. If provided, HIPP0 records an
   * outcome row for the snippets that were delivered during this session.
   */
  outcome?: {
    snippet_ids: string[];
    rating: 'positive' | 'negative' | 'neutral';
    signal_source: 'user_reaction' | 'auto_detect' | 'explicit_feedback';
  };
}

export interface HermesSessionEndResponse {
  session_id: string;
  ended_at: string;
  /** IDs of any summary snippets the distillery produced from this session. */
  summary_snippet_ids: string[];
}

// ---------------------------------------------------------------------------
// POST /api/hermes/user-facts — idempotent upsert of per-user facts
// ---------------------------------------------------------------------------

export interface HermesUserFactUpsertRequest {
  project_id: string;             // UUID, required
  external_user_id: string;       // e.g. Telegram user_id
  facts: HermesUserFact[];
}

export interface HermesUserFact {
  key: string;                    // e.g. "preferred_contact"
  value: string;                  // e.g. "phone"
  /**
   * When true, value is appended to a list under `key` instead of replacing
   * the previous value. Use for lists like `interests`.
   */
  additive?: boolean;
  /** Optional free-form source tag: "alice", "self_report", etc. */
  source?: string;
}

export interface HermesUserFactUpsertResponse {
  external_user_id: string;
  /**
   * ETag-style version string. Clients pass the last-seen version as an
   * `If-Match` header to get 409 Conflict on concurrent writes.
   */
  version: string;
  facts: HermesUserFactRecord[];
}

export interface HermesUserFactRecord {
  key: string;
  value: string;
  source: string | null;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// GET /api/hermes/user-facts — read current facts for a user
// ---------------------------------------------------------------------------

export interface HermesUserFactReadQuery {
  project_id: string;
  external_user_id: string;
}

export interface HermesUserFactReadResponse {
  external_user_id: string;
  version: string;
  facts: HermesUserFactRecord[];
}

// ---------------------------------------------------------------------------
// Existing endpoints — documented here so the Hermes side has one file to
// read. These shapes MUST match the real handlers in routes/capture.ts,
// routes/compile.ts and routes/outcomes.ts.
// ---------------------------------------------------------------------------

/** POST /api/capture — see routes/capture.ts (truth). */
export interface HermesCaptureRequest {
  project_id: string;
  agent_name: string;
  conversation: string;           // raw text, max 500_000
  session_id?: string | null;     // UUID or null; must come from session/start
  source: typeof HERMES_CAPTURE_SOURCE;  // always 'hermes'
  source_event_id?: string | null;       // e.g. Telegram message_id
  source_channel?: string | null;        // e.g. Telegram chat_id
}

export interface HermesCaptureResponse {
  capture_id: string;
  status: 'processing' | 'duplicate';
}

/** POST /api/compile — see routes/compile.ts (truth). */
export interface HermesCompileRequest {
  project_id: string;
  agent_name: string;
  task_description: string;
  max_tokens?: number;
  task_session_id?: string;       // UUID — enables prefetch cache lookup
  namespace?: string;
  session_lookback_days?: number;
  include_superseded?: boolean;
  include_role_signal?: boolean;
}

/**
 * Response shape when calling `POST /api/compile?format=json`. The default
 * response format is h0c binary — Hermes must pass `?format=json`.
 */
export interface HermesCompileResponse {
  decisions: HermesCompiledDecision[];
  total_tokens: number;
  cache_hit: boolean;
  role_signal?: Record<string, unknown> | null;
}

export interface HermesCompiledDecision {
  id: string;
  title?: string;
  text: string;
  score: number;
  source_session?: string | null;
  created_at?: string;
}

// ---------------------------------------------------------------------------
// POST /api/hermes/conversations/:session_id/messages
//
// Append a single message to a session's log. The Hermes runtime calls this
// once per turn (user + assistant + tool calls) while a session is live, so
// the web Chat view and the HermesAgents drill-down see messages in real time.
// ---------------------------------------------------------------------------

export type HermesMessageRole = 'user' | 'assistant' | 'system' | 'tool';

export interface HermesMessageAppendRequest {
  role: HermesMessageRole;
  content: string;                       // required, max 500_000
  tool_calls?: unknown;                  // JSON-serializable, optional
  tool_results?: unknown;                // JSON-serializable, optional
  tokens_in?: number;
  tokens_out?: number;
}

export interface HermesMessageAppendResponse {
  message_id: string;
  session_id: string;
  conversation_id: string;
  created_at: string;
}

/** POST /api/outcomes — see routes/outcomes.ts (truth). */
export interface HermesOutcomeRequest {
  project_id: string;
  session_id: string;
  agent_name: string;
  snippet_ids: string[];
  outcome: 'positive' | 'negative' | 'neutral';
  signal_source: 'user_reaction' | 'auto_detect' | 'explicit_feedback';
}

export interface HermesOutcomeResponse {
  recorded: boolean;
  weight_updates_scheduled: boolean;
}
